### ISSUE TITLE
Insert with returning doesn't work

### ISSUE THREAD

**Issue by pyankoff** [fukamachi/cl-dbi#28]
I'm using Postgresql and trying to return row from `insert-into` command and keep getting `; No value`:
```
(execute
     (insert-into :test
       (set= :text "asdf")
       (returning :*)))
```
SXQL seems to produce correct statement: `#<SXQL-STATEMENT: INSERT INTO test (text) VALUES ('asdf') RETURNING *>`. Is there a problem with execute or am I missing something?
Thank you!

**Comment by fukamachi** [comment]
`execute` returns no values since it's typically for insert/update/delete queries. As `RETURNING` is an original extension of PostgreSQL, I'm not so sure it should be considered.

**Comment by knobo** [comment]
You should do this to return row from insert-into
```
(datafly:retrieve-one
 (insert-into :test
   (set= :text "asdf")
   (returning :*)))
```

**Comment by pyankoff** [comment]
Hah, thank you! Didn't thought of that :)
