### ISSUE TITLE
dbi:connect somehow blocks Keyboard Interrupt

### ISSUE THREAD

**Issue by Petelliott** [fukamachi/cl-dbi#40]
in sbcl 1.4.10, running:
```lisp
(defvar *conn* (dbi:connect :mysql :database-name "db" :username "root"))
```
somehow disables the keyboard/interactive interrupt (\<C-c\>). It remains disabled when the connection
is closed.

**Comment by fukamachi** [comment]
Interesting. Perhaps, cl-mysql has this issue since no problems with PostgreSQL driver.

**Comment by Petelliott** [comment]
I just checked, the problem is in cl-mysql
